options:
    ga-view-id:
        default: ''
        description: Google Analytics view ID
        type: string
    ga-creds:
        default: ''
        description:
            Base64-encoded Google Analytics account credentials in JSON format
        type: string
    github-token:
        default: ''
        description: |
            Auth token to use for GitHub.  If not provided, GitHub API access will be
            unauthenticated and may run up against rate limits.
        type: string
